### ISSUE TITLE
keeping links and sections

### ISSUE THREAD

**Issue by andresmit** [bwbaugh/wikipedia-extractor#9]
works fine without -l option but

when trying to run: python WikiExtractor.py -l wiki.xml 

i get:

INFO: Preprocessing dump to collect template definitions: this may take some time.
INFO: Starting processing pages from wiki.xml.
INFO: Using 2 CPUs.
INFO: 1 Ajalugu
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "WikiExtractor.py", line 2335, in run
    job.extract(self._splitter)
  File "WikiExtractor.py", line 407, in extract
    text = clean(self, text)
  File "WikiExtractor.py", line 1877, in clean
    text = replaceInternalLinks(text)
  File "WikiExtractor.py", line 1486, in replaceInternalLinks
    res += text[cur:s] + makeInternalLink(title, label) + trail
  File "WikiExtractor.py", line 1764, in makeInternalLink
    return '<a href="%s">%s</a>' % (urllib.quote(title.encode('utf-8')), anchor)
NameError: global name 'anchor' is not defined

**Comment by jogeiss** [comment]
Hi there,
I had the same problem, but it is easy to solve:
In line 1764 just replace "anchor" with "label". The function "def makeInternalLink(title, label):" gets the variable label instead of anchor...

Thanks for this great tool!

Best,
Johanna

**Comment by andresmit** [comment]
thanks a bunch. works!
